# Generated by Django 4.2.5 on 2023-09-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Imanza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=15)),
                ('style_de_danse', models.CharField(max_length=100)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Imanza.agenda')),
            ],
        ),
        migrations.DeleteModel(
            name='Danseur',
        ),
    ]
